dist: trusty
language: java
sudo: false
jdk:
  - oraclejdk11

git:
  depth: 2 #clone repository to a maximum depth of 2 commits

script: "./gradlew clean assemble"

after_success:
  - ./gradlew integration
