spring:
  datasource:
    url: jdbc:mysql://localhost:${DB_PORT:3306}/${DB_NAME:goal_list}?allowPublicKeyRetrieval=true&useSSL=FALSE
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

logging:
  level:
    org:
      hibernate:
        SQL: debug
